# Based on this tutorial: https://www.youtube.com/watch?v=D9CLhQdLp8w&ab_channel=ShawhinTalebi
title: Margaret Sabelhaus
logo: IMG_9786.JPG
description: Data Scientist in Denver, CO
show_downloads: false
theme: jekyll-theme-minimal
